import = [
  #"~/.config/alacritty/themes/themes/solarized_osaka.toml",
  "~/.config/alacritty/themes/themes/rose-pine.toml",
]

[env]
TERM = "xterm-256color"

# Window configuration
[window]
dimensions = { columns = 132, lines = 30 }
padding = { x = 0, y = 0}
dynamic_padding = true
decorations = "None"
startup_mode = "Windowed"
#opacity = 0.7
#blur = true


# Scrolling configuration
[scrolling]
history = 10000
multiplier = 3

# Font configuration
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0
